on:
  push:
    branches:
    - test

jobs:
  terraform-plan:
    name: 'test download artifacts'
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
    # Downloading after checkout 
    - name: Download PR Artifact
      uses: dawidd6/action-download-artifact@v6
      with:
        workflow: upload.yaml # Must match the filename of Workflow 1
        workflow_conclusion: success
        # Search across PR workflows to find the artifact
        event: pull_request
    - name: listing
      run: |
        ls -lh
        echo ima here
    - name: check
      run: |
        EXIT_CODE=$(cat tfplan/exitcode)
        echo $EXIT_CODE
        if [[ "$EXIT_CODE" == "0" ]]; then
          echo "ok"
          exit 0
        fi
    - name: listing2
      run: |
        ls -lh
        echo 'ima still here'

