name: Get Status Sample Workflow

on:
  workflow_dispatch:
jobs:
  get-status:
    runs-on: ubuntu-latest
    steps:
      - name: Get Status of current ref
        id: get-status
        uses: danieldeichfuss/get-status@v0
        with:
          ref: main
