name: Trigger Jenkins Job on PR

# github.rest.repos.createCommitStatus({
            #   owner: context.repo.owner,
            #   repo: context.repo.repo,
            #   sha: context.payload.pull_request.merge_commit_sha,
            #   state: "pending",
            #   context: "Jenkins Unit Tests",
            #   description: "Tests are running in Jenkins"
            # })

on:
  pull_request:

jobs:
  trigger-jenkins:
    name: Trigger Jenkins Job
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - name: Set PR status to pending
        uses: actions/github-script@v6
        with:
          script: |
            console.log(context.payload.pull_request.number)

      - name: Trigger Jenkins Job
        run: |
          echo hello
